<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('customer_qr_codes', function (Blueprint $table) {
            $table->id();

            $table->foreignId('customer_id')
                ->constrained('customers')
                ->restrictOnDelete()
                ->cascadeOnUpdate();

            // Random 64-character token generated by Laravel.
            $table->char('qr_token', 64)->unique();

            $table->boolean('is_active')->default(true);

            $table->timestamp('created_at')
                ->useCurrent();

            $table->timestamp('revoked_at')
                ->nullable();

            $table->index(
                'customer_id',
                'idx_qr_customer'
            );

            $table->index(
                'is_active',
                'idx_qr_active'
            );
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('customer_qr_codes');
    }
};